SolverParameters:
  max_number_of_iterations: 1000
  max_cpu_time: 0
  QPoasesParameters:
    enableRamping: 0
    enableFarBounds: 1
    enableFlippingBounds: 0
    enableRegularisation: 1
    enableFullLITests: 0
    enableNZCTests: 0
    enableDriftCorrection: 0
    enableCholeskyRefactorisation: 0
    enableEqualities: 1
    terminationTolerance: 2.221e-07
    boundTolerance: 2.221e-10
    boundRelaxation: 10000
    epsNum: -2.221e-13
    epsDen: 2.221e-13
    maxPrimalJump: 100000000
    maxDualJump: 100000000
    initialRamping: 0.5
    finalRamping: 1
    initialFarBounds: 1000000
    growFarBounds: 1000
    initialStatusBounds: 0
    epsFlipping: 2.221e-13
    numRegularisationSteps: 1
    epsRegularisation: 2.221e-13
    numRefinementSteps: 0
    epsIterRef: 2.221e-14
    epsLITests: 2.221e-11
    epsNZCTests: 6.663e-13
    rcondSMin: 1e-14
    enableInertiaCorrection: 1
    enableDropInfeasibles: 0
    dropBoundPriority: 1
    dropEqConPriority: 1
    dropIneqConPriority: 1